### ISSUE TITLE
Tips are not found in different screen from currentTip during TipTour 

### ISSUE THREAD

**Issue by griimick** [MaiconGilton/react-native-tip#4]
Thank you for sharing this library. Very insightful.

I think there is a limitation in TipTour implementation. It fails to find nextTips when they are present in a different screen which is not loaded (Tip is not registered) until we navigate to that screen.

I think we should call nextAction/prevAction before finding the tip by id in the registry. So that once nextAction is called, 

- we navigate to the screen, 
- the tip is registered 
- then we can find it after some predefined delay (depending time for navigation animation + set layout)

**Comment by Gaohaoyang** [comment]
Totally agree. I am facing this problem too.

**Comment by MaiconGilton** [comment]
Thanks for let me know! I will take a look on that.
